use std::fmt::Write;

use anyhow::Result;
use serde::Serialize;

use crate::manifest::{BackendAdapterManifest, EntityFieldManifest, ExpectedSchemaManifest};

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct GeneratedSchemaFile<'a> {
    expected_schema: &'a ExpectedSchemaManifest,
}

pub fn export_expected_schema(manifest: &BackendAdapterManifest) -> Result<String> {
    Ok(format!(
        "{}\n",
        serde_json::to_string_pretty(&GeneratedSchemaFile {
            expected_schema: &manifest.database.expected_schema,
        })?
    ))
}

pub fn export_typescript_client_bindings(manifest: &BackendAdapterManifest) -> Result<String> {
    let expected_schema_json = serde_json::to_string_pretty(&manifest.database.expected_schema)?;
    let auth_endpoints_json = serde_json::to_string_pretty(&manifest.auth.rest.paths)?;
    let mut output = String::new();

    writeln!(&mut output, "// Generated by e2ee-backend-adapter. Do not edit manually.")?;
    writeln!(&mut output, "// Manifest: {}", manifest.name)?;
    writeln!(&mut output)?;
    writeln!(&mut output, "import {{")?;
    writeln!(&mut output, "  createRestTransportFromExpectedSchema,")?;
    writeln!(&mut output, "  createEntitySchemaFromExpectedSchemaEntity,")?;
    writeln!(&mut output, "  createRestCrudAdapterFromExpectedSchemaEntity,")?;
    writeln!(&mut output, "  createRestPasswordAuthConfig,")?;
    writeln!(&mut output, "  type BackendAdapterExpectedSchemaManifest,")?;
    writeln!(&mut output, "  type CreateGeneratedRestTransportOptions,")?;
    writeln!(&mut output, "  type CreateGeneratedEntitySchemaOptions,")?;
    writeln!(&mut output, "  type EncryptedFieldValue,")?;
    writeln!(&mut output, "  type EntitySchema,")?;
    writeln!(&mut output, "  type FetchRestTransport,")?;
    writeln!(&mut output, "  type RestCrudAdapter,")?;
    writeln!(&mut output, "  type RestPasswordAuthConfig,")?;
    writeln!(&mut output, "  type RestTransport,")?;
    writeln!(&mut output, "}} from \"e2ee-client-backend\";")?;
    writeln!(&mut output)?;

    writeln!(&mut output, "export interface SessionUser {{")?;
    writeln!(&mut output, "  email: string;")?;
    writeln!(&mut output, "  id: string;")?;
    writeln!(&mut output, "}}")?;
    writeln!(&mut output)?;

    for entity in &manifest.database.expected_schema.entities {
        let alias_base = pascal_case(&entity.name);
        writeln!(
            &mut output,
            "export type {alias_base}Entity = {};",
            typescript_object_type_for_fields(&entity.fields, false),
        )?;
        writeln!(
            &mut output,
            "export type {alias_base}RemoteRecord = {};",
            typescript_object_type_for_fields(&entity.fields, true),
        )?;
        writeln!(&mut output, "export type {alias_base}Id = {};", resolve_id_type(entity))?;
        writeln!(&mut output)?;
    }

    writeln!(&mut output, "export const expectedSchema = {expected_schema_json} satisfies BackendAdapterExpectedSchemaManifest;")?;
    writeln!(&mut output)?;
    writeln!(&mut output, "export const restAuthEndpoints = {auth_endpoints_json} as const;")?;
    writeln!(&mut output)?;
    writeln!(&mut output, "export function createRestTransport(")?;
    writeln!(&mut output, "  options: CreateGeneratedRestTransportOptions = {{}},")?;
    writeln!(&mut output, "): FetchRestTransport {{")?;
    writeln!(&mut output, "  return createRestTransportFromExpectedSchema(expectedSchema, options);")?;
    writeln!(&mut output, "}}")?;
    writeln!(&mut output)?;
    writeln!(&mut output, "export function createRestAuthConfig(")?;
    writeln!(&mut output, "  transport: RestTransport = createRestTransport(),")?;
    writeln!(&mut output, "): RestPasswordAuthConfig<SessionUser> {{")?;
    writeln!(&mut output, "  return createRestPasswordAuthConfig<SessionUser>({{")?;
    writeln!(&mut output, "    endpoints: restAuthEndpoints,")?;
    writeln!(&mut output, "    transport,")?;
    writeln!(&mut output, "  }});")?;
    writeln!(&mut output, "}}")?;
    writeln!(&mut output)?;

    writeln!(&mut output, "export interface GeneratedSchemaOptions {{")?;
    for entity in &manifest.database.expected_schema.entities {
        writeln!(
            &mut output,
            "  {}?: CreateGeneratedEntitySchemaOptions;",
            typescript_property_name(&entity.name),
        )?;
    }
    writeln!(&mut output, "}}")?;
    writeln!(&mut output)?;

    writeln!(&mut output, "export interface GeneratedEntitySchemas {{")?;
    for entity in &manifest.database.expected_schema.entities {
        let alias_base = pascal_case(&entity.name);
        writeln!(
            &mut output,
            "  {}: EntitySchema<{}Entity, {}RemoteRecord, {}Id>;",
            typescript_property_name(&entity.name),
            alias_base,
            alias_base,
            alias_base,
        )?;
    }
    writeln!(&mut output, "}}")?;
    writeln!(&mut output)?;

    writeln!(&mut output, "export function createEntitySchemas(")?;
    writeln!(&mut output, "  options: GeneratedSchemaOptions = {{}},")?;
    writeln!(&mut output, "): GeneratedEntitySchemas {{")?;
    writeln!(&mut output, "  return {{")?;
    for (index, entity) in manifest.database.expected_schema.entities.iter().enumerate() {
        let alias_base = pascal_case(&entity.name);
        writeln!(
            &mut output,
            "    {}: createEntitySchemaFromExpectedSchemaEntity(",
            typescript_property_name(&entity.name),
        )?;
        writeln!(&mut output, "      expectedSchema.entities[{index}]!,")?;
        writeln!(
            &mut output,
            "      {},",
            typescript_member_access("options", &entity.name),
        )?;
        writeln!(
            &mut output,
            "    ) as EntitySchema<{}Entity, {}RemoteRecord, {}Id>,",
            alias_base,
            alias_base,
            alias_base,
        )?;
    }
    writeln!(&mut output, "  }};")?;
    writeln!(&mut output, "}}")?;
    writeln!(&mut output)?;

    writeln!(&mut output, "export interface GeneratedRestCrudAdapters {{")?;
    for entity in &manifest.database.expected_schema.entities {
        let alias_base = pascal_case(&entity.name);
        writeln!(
            &mut output,
            "  {}: RestCrudAdapter<{}RemoteRecord, {}Id>;",
            typescript_property_name(&entity.name),
            alias_base,
            alias_base,
        )?;
    }
    writeln!(&mut output, "}}")?;
    writeln!(&mut output)?;

    writeln!(&mut output, "export function createRestCrudAdapters(")?;
    writeln!(&mut output, "  transport: RestTransport = createRestTransport(),")?;
    writeln!(&mut output, "): GeneratedRestCrudAdapters {{")?;
    writeln!(&mut output, "  return {{")?;
    for (index, entity) in manifest.database.expected_schema.entities.iter().enumerate() {
        let alias_base = pascal_case(&entity.name);
        writeln!(
            &mut output,
            "    {}: createRestCrudAdapterFromExpectedSchemaEntity<{}RemoteRecord, {}Id>(",
            typescript_property_name(&entity.name),
            alias_base,
            alias_base,
        )?;
        writeln!(&mut output, "      expectedSchema.entities[{index}]!,")?;
        writeln!(&mut output, "      transport,")?;
        writeln!(&mut output, "    ),")?;
    }
    writeln!(&mut output, "  }};")?;
    writeln!(&mut output, "}}")?;

    Ok(format!("{output}\n"))
}

fn resolve_id_type(entity: &crate::manifest::ExpectedSchemaEntityManifest) -> String {
    entity
        .fields
        .iter()
        .find(|field| field.entity_path == entity.id_path)
        .map(|field| typescript_scalar_type(&field.entity_type).to_owned())
        .unwrap_or_else(|| "string".to_owned())
}

fn typescript_object_type_for_fields(fields: &[EntityFieldManifest], remote: bool) -> String {
    let fragments = fields
        .iter()
        .map(|field| {
            let type_expr = if remote {
                typescript_field_type(field, true)
            } else {
                typescript_field_type(field, false)
            };
            let path = if remote {
                field.remote_path.as_str()
            } else {
                field.entity_path.as_str()
            };

            typescript_path_fragment(path, &type_expr, field.optional)
        })
        .collect::<Vec<_>>();

    if fragments.is_empty() {
        "Record<string, never>".to_owned()
    } else {
        fragments.join(" & ")
    }
}

fn typescript_field_type(field: &EntityFieldManifest, remote: bool) -> String {
    let base = if remote && field.encrypted {
        "EncryptedFieldValue".to_owned()
    } else if remote {
        typescript_scalar_type(&field.remote_type).to_owned()
    } else {
        typescript_scalar_type(&field.entity_type).to_owned()
    };

    if field.nullable {
        format!("{base} | null")
    } else {
        base
    }
}

fn typescript_scalar_type(schema_type: &str) -> &'static str {
    match schema_type {
        "array" => "unknown[]",
        "boolean" => "boolean",
        "number" => "number",
        "object" => "Record<string, unknown>",
        "string" => "string",
        "json" | "unknown" => "unknown",
        _ => "unknown",
    }
}

fn typescript_path_fragment(path: &str, type_expr: &str, optional: bool) -> String {
    let segments = path.split('.').collect::<Vec<_>>();
    typescript_nested_fragment(&segments, type_expr, optional)
}

fn typescript_nested_fragment(segments: &[&str], type_expr: &str, optional: bool) -> String {
    let property = typescript_property_name(segments[0]);
    let optional_marker = if optional { "?" } else { "" };

    if segments.len() == 1 {
        return format!("{{ {property}{optional_marker}: {type_expr} }}");
    }

    let inner = typescript_nested_fragment(&segments[1..], type_expr, optional);
    format!("{{ {property}{optional_marker}: {inner} }}")
}

fn typescript_property_name(name: &str) -> String {
    if is_typescript_identifier(name) {
        name.to_owned()
    } else {
        format!("\"{}\"", name.replace('"', "\\\""))
    }
}

fn typescript_property_access(name: &str) -> String {
    if is_typescript_identifier(name) {
        name.to_owned()
    } else {
        format!("[\"{}\"]", name.replace('"', "\\\""))
    }
}

fn typescript_member_access(target: &str, name: &str) -> String {
    let property_access = typescript_property_access(name);

    if property_access.starts_with('[') {
        format!("{target}{property_access}")
    } else {
        format!("{target}.{property_access}")
    }
}

fn is_typescript_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    if !(first == '_' || first == '$' || first.is_ascii_alphabetic()) {
        return false;
    }

    chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

fn pascal_case(value: &str) -> String {
    let mut output = String::new();
    let mut capitalize = true;

    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize {
                output.push(ch.to_ascii_uppercase());
                capitalize = false;
            } else {
                output.push(ch);
            }
        } else {
            capitalize = true;
        }
    }

    if output.is_empty() {
        "GeneratedEntity".to_owned()
    } else {
        output
    }
}

#[cfg(test)]
mod tests {
    use super::{export_expected_schema, export_typescript_client_bindings};
    use crate::manifest::{
        AuthManifest, BackendAdapterManifest, DatabaseManifest, EntityFieldManifest,
        EntityManifest, EntityRestManifest, ExpectedEntityTableManifest,
        ExpectedSchemaApiManifest, ExpectedSchemaEntityApiManifest,
        ExpectedSchemaRestApiManifest,
        ExpectedSchemaEntityManifest, ExpectedSchemaManifest, RestAuthManifest,
        RestAuthPaths, SessionCookieNames, SessionManifest,
    };

    fn manifest() -> BackendAdapterManifest {
        BackendAdapterManifest {
            auth: AuthManifest {
                mode: "password-session".to_owned(),
                rest: RestAuthManifest {
                    paths: RestAuthPaths {
                        get_kdf_salt: "/auth/kdf-salt".to_owned(),
                        login: "/auth/login".to_owned(),
                        logout: "/auth/logout".to_owned(),
                        refresh: "/auth/refresh".to_owned(),
                        register_begin: "/auth/register-begin".to_owned(),
                        register_complete: "/auth/register-complete".to_owned(),
                    },
                },
                session: SessionManifest {
                    cookie_names: SessionCookieNames {
                        refresh: "refresh".to_owned(),
                        session: "session".to_owned(),
                    },
                    refresh_duration_seconds: 3600,
                    session_duration_seconds: 600,
                },
            },
            database: DatabaseManifest {
                engine: "postgres".to_owned(),
                expected_schema: ExpectedSchemaManifest {
                    api: ExpectedSchemaApiManifest {
                        rest: ExpectedSchemaRestApiManifest {
                            base_url: "/api".to_owned(),
                            default_headers: None,
                        },
                        api_type: "rest".to_owned(),
                    },
                    auth_tables: vec!["users".to_owned(), "sessions".to_owned()],
                    entities: vec![ExpectedSchemaEntityManifest {
                        api: ExpectedSchemaEntityApiManifest {
                            rest: EntityRestManifest {
                                allow_create: true,
                                allow_delete: true,
                                allow_get_by_id: true,
                                allow_list: true,
                                allow_update: true,
                                base_path: "/notes".to_owned(),
                            },
                            api_type: "rest".to_owned(),
                        },
                        fields: vec![
                            EntityFieldManifest {
                                encrypted: true,
                                entity_path: "content".to_owned(),
                                entity_type: "string".to_owned(),
                                nullable: false,
                                optional: false,
                                remote_path: "content".to_owned(),
                                remote_type: "string".to_owned(),
                                strategy_id: Some("aes-256-gcm".to_owned()),
                            },
                            EntityFieldManifest {
                                encrypted: false,
                                entity_path: "id".to_owned(),
                                entity_type: "string".to_owned(),
                                nullable: false,
                                optional: false,
                                remote_path: "id".to_owned(),
                                remote_type: "string".to_owned(),
                                strategy_id: None,
                            },
                            EntityFieldManifest {
                                encrypted: false,
                                entity_path: "metadata.tags".to_owned(),
                                entity_type: "array".to_owned(),
                                nullable: true,
                                optional: true,
                                remote_path: "metadata.tags".to_owned(),
                                remote_type: "array".to_owned(),
                                strategy_id: None,
                            },
                        ],
                        id_path: "id".to_owned(),
                        name: "note".to_owned(),
                        primary_key: "id".to_owned(),
                        table_name: "notes".to_owned(),
                    }],
                    entity_tables: vec![ExpectedEntityTableManifest {
                        primary_key: "id".to_owned(),
                        table_name: "notes".to_owned(),
                    }],
                },
            },
            entities: vec![EntityManifest {
                fields: vec![EntityFieldManifest {
                    encrypted: false,
                    entity_path: "id".to_owned(),
                    entity_type: "string".to_owned(),
                    nullable: false,
                    optional: false,
                    remote_path: "id".to_owned(),
                    remote_type: "string".to_owned(),
                    strategy_id: None,
                }],
                id_path: "id".to_owned(),
                name: "note".to_owned(),
                rest: EntityRestManifest {
                    allow_create: true,
                    allow_delete: true,
                    allow_get_by_id: true,
                    allow_list: true,
                    allow_update: true,
                    base_path: "/notes".to_owned(),
                },
                table_name: "notes".to_owned(),
            }],
            name: "notes-service".to_owned(),
            realtime: None,
            version: crate::manifest::MANIFEST_VERSION,
        }
    }

    #[test]
    fn export_expected_schema_wraps_expected_schema() {
        let json = export_expected_schema(&manifest()).expect("expected schema should export");

        assert!(json.contains("\"expectedSchema\""));
        assert!(json.contains("\"api\""));
    }

    #[test]
    fn export_typescript_client_bindings_includes_auth_and_entity_types() {
        let source = export_typescript_client_bindings(&manifest())
            .expect("typescript bindings should export");

        assert!(source.contains("export interface SessionUser"));
        assert!(source.contains("export function createRestTransport"));
        assert!(source.contains("export type NoteEntity = { content: string } & { id: string } & { metadata?: { tags?: unknown[] | null } }"));
        assert!(source.contains("export type NoteRemoteRecord = { content: EncryptedFieldValue } & { id: string } & { metadata?: { tags?: unknown[] | null } }"));
        assert!(source.contains("export function createRestAuthConfig"));
        assert!(source.contains("export function createEntitySchemas"));
        assert!(source.contains("export function createRestCrudAdapters"));
        assert!(source.contains("createRestTransportFromExpectedSchema(expectedSchema, options)"));
        assert!(source.contains("\"/auth/login\""));
    }
}
